### ISSUE TITLE
Allow override for color output

### ISSUE THREAD

**Issue by swarkentin** [devashishdxt/cli-table#11]
It would be great if we could override the `ColorChoice` used in for the purpose of writing unit tests:

https://github.com/devashishdxt/cli-table/blob/e352baf8e7fb8cf9375aeaaa48c0943165bbd38e/src/table.rs#L35

This is making it difficult to automate testing the output of a table formatted with the library when examining `stdout`.

**Comment by devashishdxt** [comment]
Added a function to do this in latest release. https://crates.io/crates/cli-table

**Comment by swarkentin** [comment]
The change works perfectly - thank you!!
