### ISSUE TITLE
Add borderless style table

### ISSUE THREAD

**Issue by oreksu** [devashishdxt/cli-table#13]
I did the following, but it would be nice to have such option by default.

```
trait Borderless {
    fn withpout_border(self) -> Self;
}

impl Borderless for cli_table::TableStruct {
    fn withpout_border(self) -> cli_table::TableStruct {
        let empty_horisontal_line = cli_table::format::HorizontalLine::new(' ', ' ', ' ', ' ');
        let empty_vertical_line = cli_table::format::VerticalLine::new(' ');
        let empty_border = cli_table::format::Border::builder()
            .top(empty_horisontal_line)
            .bottom(empty_horisontal_line)
            .left(empty_vertical_line)
            .right(empty_vertical_line)
            .build();
        self.border(empty_border)
    }
}
```

**Comment by devashishdxt** [comment]
Thanks @olitus for creating this issue. I'll look into this.

**Comment by devashishdxt** [comment]
On a side note. If you want to create a borderless table, it is very easy:

```rust
fn get_table() -> TableStruct {
    // Creates `TableStruct` object
}

fn print_table() {
    let table = get_table().border(Border::builder().build()); // Attaches an empty border to the table
    print_stdout(table).unwrap();
}
```

**Comment by olitus** [comment]
@devashishdxt That makes a lot of sense. Maybe simply updating README.md to include how to create table without border would be good. Cause I did not find any information in the README.md and started looking through structs, etc.

Anyway, thank you for maintaining such a great library! You helped me a lot with my personal project 😄

**Comment by devashishdxt** [comment]
I've added styling documentation in README. It'll be released with new version on crates.io.
