### ISSUE TITLE
Support for other writers

### ISSUE THREAD

**Issue by wojciech-zurek** [devashishdxt/cli-table#17]
How to write table output to String (or impl `Display` trait) or different structs that impl for example trait `Write`: String, File, BufWriter etc...?
Right now we can only use `print_stdout ` and `print_stderr`

Example:
```
impl Display for TestStruct {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    let writer = ....get writer;
    let table = ...get table;
    table.write(writer) 
    or
    cli_table::write_table(table, writer) //similar to print_stdout
   or
   let ts =  table.to_string();
}
```

**Comment by devashishdxt** [comment]
Thanks for creating an issue for this. I'll see if there's an easy way to support this.
