### ISSUE TITLE
Tabs in source text result in misaligned table borders

### ISSUE THREAD

**Issue by briankung** [devashishdxt/cli-table#25]
Hopefully I'll be able to post a minimal reproducible example soon, but it should be easy to recreate. Just have a multi-line string as one of the cell values and include tabs in some of the lines.

Thanks for the great crate! As a stop-gap measure I just replaced the tabs with spaces when displaying the table.

**Comment by devashishdxt** [comment]
Thanks for creating this issue.

This crate uses `unicode-width` to calculate display width of a string and it has an open issue for this: https://github.com/unicode-rs/unicode-width/issues/6

I'm not sure there's a good workaround right now other than replacing tabs with spaces. Other crates which depend on `unicode-width` also have the same issue.

**Comment by briankung** [comment]
Ah, gotcha. Happy to close this and follow the other issue. Thanks for pointing me towards it!
