### ISSUE TITLE
Won't Compile

### ISSUE THREAD

**Issue by nitaigao** [devashishdxt/cli-table#4]
Thanks for creating such an awesome module

Any idea how to fix this compilation error?

```
error: enum variants on type aliases are experimental
   --> src/format/cell.rs:103:9
    |
103 |         Self::Left
    |         ^^^^^^^^^^

error: enum variants on type aliases are experimental
   --> src/format/cell.rs:121:9
    |
121 |         Self::Top
    | 
```

**Comment by devashishdxt** [comment]
Hi @nitaigao,

May I know the version of rust compiler are you using? Type aliases for enum variants were stabilised in 1.37.0

https://github.com/rust-lang/rust/pull/61682/

You can try running `rustup update` and then compile the code.

Let me know if you continue to face this issue after updating Rust version.

**Comment by nitaigao** [comment]
Thanks @devashishdxt. You were totally right, i had an old version of rust installed. 

Many thanks for the detailed reply and sorry for the hassle.
