### ISSUE TITLE
Padding

### ISSUE THREAD

**Issue by rakshith-ravi** [devashishdxt/cli-table#7]
Thanks for this library. It's quite easy to use.

Would it be possible to add padding to the table? Say 1 unit left padding and 1 unit right padding such that the cell always has padding to the left and right? Perhaps we can incorporate this into the builder?

**Comment by devashishdxt** [comment]
This is a good idea. I'll try to add this when I get some time to work on it. In the meantime, you're welcome to work on this. PRs are always appreciated.

**Comment by devashishdxt** [comment]
Support for padding was added in [latest release](https://github.com/devashishdxt/cli-table/releases/tag/0.3.1). Closing this issue.
