### ISSUE TITLE
Set table color

### ISSUE THREAD

**Issue by bytebuddha** [devashishdxt/cli-table#8]
Hey I really like this library it's saved me a lot of time on a few side projects thanks for writing it.

I would like too be able to set the color of the table borders/seperators to a different color. I've temperalily made some changes to add a color field to the TableFormat struct that will do this. Thinking this would be the best place for a 'global' color that would affect both Border/Seperators. Would you like me too submit PR with these changes?

**Comment by devashishdxt** [comment]
@bytebuddha Sure, please submit a PR!
